[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tybuild"
version = "0.1.0"
requires-python = ">=3.6"

[project.scripts]
tybuild = "tybuild.cli:main"
